//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveProject
    {
        public ActiveProject()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int Project { get; set; }
        public int Freelancer { get; set; }
    
        public virtual Project Project1 { get; set; }
        public virtual ICollection<Task> Task { get; set; }
    }
}
