//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public int AttachedFile { get; set; }
        public string Description { get; set; }
        public int Task { get; set; }
    
        public virtual AttachedFile AttachedFile1 { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
