//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousWorkLinks
    {
        public int Id { get; set; }
        public Nullable<int> Profile { get; set; }
        public string Link { get; set; }
    
        public virtual Profile Profile1 { get; set; }
    }
}
