//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Tecnologies_X_Profile = new HashSet<Tecnologies_X_Profile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FK_User { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tecnologies_X_Profile> Tecnologies_X_Profile { get; set; }
    }
}
