//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.PreviousWorkLinks = new HashSet<PreviousWorkLinks>();
            this.ProfileTechnologies = new HashSet<ProfileTechnologies>();
        }
    
        public virtual int Id { get; set; }
        public virtual int User { get; set; }
        public virtual string PhoneNumber { get; set; }
        public virtual string Description { get; set; }
        public virtual int Country { get; set; }
        public virtual byte[] Picture { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual ICollection<PreviousWorkLinks> PreviousWorkLinks { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ProfileTechnologies> ProfileTechnologies { get; set; }
    }
}
