//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ActiveProject = new HashSet<ActiveProject>();
            this.Offers = new HashSet<Offers>();
            this.ProjectRating = new HashSet<ProjectRating>();
        }
    
        public int Id { get; set; }
        public int Company { get; set; }
        public string Description { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime SatartDate { get; set; }
        public double Budget { get; set; }
    
        public virtual ICollection<ActiveProject> ActiveProject { get; set; }
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProjectRating> ProjectRating { get; set; }
    }
}
