//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public int ActiveProject { get; set; }
        public int TaskRate { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ActiveProject ActiveProject1 { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual TaskState TaskState { get; set; }
    }
}
