//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnologies_X_Profile
    {
        public int Id { get; set; }
        public int FK_Profile { get; set; }
        public int FK_Technology { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
