//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Offers = new HashSet<Offers>();
            this.Profile = new HashSet<Profile>();
            this.Project = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public int User_Type { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
