//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Profile = new HashSet<Profile>();
            this.Project = new HashSet<Project>();
            this.Project1 = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public int FK_User_Type { get; set; }
    
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Project> Project1 { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
